# Generated by Django 3.2.8 on 2021-12-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='unauth_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField(unique=True)),
                ('is_spam', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
    ]
