# Generated by Django 3.2.8 on 2021-12-16 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caller', '0003_alter_myuser_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='unauth_users',
            new_name='UnauthUsers',
        ),
    ]
