# Generated by Django 3.2.8 on 2021-12-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caller', '0004_rename_unauth_users_unauthusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unauthusers',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
    ]
