# Generated by Django 3.2.8 on 2021-12-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caller', '0005_alter_unauthusers_is_spam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='unauthusers',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
