# Generated by Django 3.2.8 on 2021-12-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caller', '0006_auto_20211216_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_spam',
        ),
        migrations.RemoveField(
            model_name='unauthusers',
            name='is_spam',
        ),
        migrations.AddField(
            model_name='myuser',
            name='spam_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unauthusers',
            name='spam_count',
            field=models.IntegerField(default=0),
        ),
    ]
